type1:
  databases:
    - db_type1_1
    - db_type1_2
    - db_type1_3
  # number of databases on which to run concurrent queries
  # normally choose concurrency <= len(databases) but more can work
  # fine too; the number here sets the number of query consumer
  # goroutines
  concurrency: 3
  # how many times to run the queries on each database until
  # moving onto the next database (if appropriate)
  iterations: 3
  queries:
    - select * from function()
    - select 1
    - select pg_sleep(5)

type2:
  databases: [db_type2_1, db_type2_2, db_type2_3]
  concurrency: 2
  iterations: 2
  queries:
    - >
      select * from function()
    - >
      select 1
    - >
      select pg_sleep(5)
